---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'data/**'
      - 'json_interaction/**'
      - '.github/**'
      - '.github/**/*'
      - 'README.md'
exclude_paths:
  - 'data/**'
  - 'json_interaction/**'
  - '.github/**'
  - '.github/**/*'
  - 'README.md'
