---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'
      - 'gator/checks/**'
      - '.github/**'
      - '.github/**/*'
      - 'README.md'
exclude_paths:
  - 'tests/**'
  - '.github/**'
  - '.github/**/*'
  - 'README.md'

